version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        Version: 1.0
    image: api_online:1.0
    container_name: api_online
    restart: always
    # env_file: .env
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=community
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=long_random_pass_redis
    ports:
      - "10030:3000"
      - "10031:3001"
    volumes:
      - /home/imooc/online:/app/public
    networks:
      - webapp-network  

  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  redis:
    image: redis
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass long_random_pass_redis

networks:
  webapp-network:
    driver: bridge
